export const dailyProducts = [
  {
    _id: 1,
    productName: "Collagen Gummies",
    ficheTech: [
      { label: "Helps speed up and normalize the digestion process" },
      {
        label:
          "Assists in healthy weight loss without a negative impact on your health",
      },
      { label: "Helps speed up and normalize the digestion process" },
      {
        label:
          "Assists in healthy weight loss without a negative impact on your health",
      },
      { label: "Increases the reserves of energy in your body" },
      { label: "Safe with no side effects" },
      { label: "Controls blood sugar levels" },
      { label: "Help keep your muscles lean" },
      { label: "Helps improve cognitive functions" },
    ],
    brand: "Other",
    badge: false,
    des: { en: "" },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 1360,
    img: "/images/Daily-Herbals-Collagen.jpeg",
  },
  {
    _id: 2,
    productName: "Cleanse Pro",
    ficheTech: [
      { label: "Helps speed up and normalize the digestion process" },
      {
        label:
          "Assists in healthy weight loss without a negative impact on your health",
      },
      { label: "Helps speed up and normalize the digestion process" },
      {
        label:
          "Assists in healthy weight loss without a negative impact on your health",
      },
      { label: "Increases the reserves of energy in your body" },
      { label: "Safe with no side effects" },
      { label: "Controls blood sugar levels" },
      { label: "Help keep your muscles lean" },
      { label: "Helps improve cognitive functions" },
    ],
    brand: "Other",
    badge: false,
    des: {
      en: "Ingredients: Flaxseed 400mg (40%), Oat Bran 300mg (30%), Papya Leaf Extract 70mg (7%), Black Walnut Hull 30mg (3%), Prune Extract 100mg (10%), Aloe Vera 50mg (5%), L. Acidophilus 10mg (1%), Apple Pectin 40mg (4%), blended 1000mg.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 1700,
    img: "/images/Daily-Herbals-Cleanse.jpeg",
  },
  {
    _id: 3,
    productName: "GenBrain",
    ficheTech: [],
    brand: "Other",
    badge: false,
    des: { en: "" },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 1020,
    img: "/images/Daily-Gerbals-GenBrain.jpeg",
  },
  {
    _id: 4,
    productName: "Skincell Advanced",
    ficheTech: [],
    brand: "Other",
    badge: false,
    des: {
      en: "Ingredients: Water 158mg (15.8%), Cetearyl Alcohol 165mg (16.5%), Caprylic/Capric Triglycerides 67mg (6.7%), Glycerin 61mg (6.1%), Ceteareth 58mg (5.8%), Butyrospermum Parkii Butter 55mg (5.5%), Butylene Glycol 51mg (5.1%), Palmitoyl Oligopeptide 48mg (4.8%), Palmitoyl Tetrapeptide 46mg (4.6%), Octyldodecanol 41mg (4.1%), Ethyhexyl Palmitate 33mg (3.3%), Zea Mays Oil 31mg (3.1%), Tocopheryl Acetate 31mg (3.1%), Cholecalciferol 28mg (2.8%), Retinyl Palmitate 20mg (2%), Ascorbic Acid 19mg (1.9%), Pyridoxine HCl 15mg (1.5%), Silica 15mg (1.5%), Sodium Propoxyhydroxypropyl Thiosulfate Silica 14mg (1.4%), Carbomer 10mg",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 680,
    img: "/images/Daily-Herbals-Skincell-Advanced.jpeg",
  },
  {
    _id: 5,
    productName: "CANADIAN OATS N' PROTEIN",
    ficheTech: [],
    brand: "Other",
    badge: false,
    des: {
      en: "Oats n’ Protein was designed for the exact demands of on-the-go individuals who require a healthy dose of the highest quality (gluten-free) carbohydrates and high protein to stay full, focused, and fueled. Our convenient single serving cups are the ideal post-workout snack or commuter friendly breakfast, while our multi-serving 500g bags are the perfect balanced and customizable start to the day!",
    },
    cat: "Proteins",
    pdf: "",
    extraInfo: "GMO-free",
    price: 800,
    img: "/images/quickOats.png",
  },
  {
    _id: 6,
    productName: "TRANS4ORM FAT BURNER POWDER",
    ficheTech: [],
    brand: "Other",
    badge: false,
    des: {
      en: "TRANS4ORM® is a scientifically-developed multi-stage thermogenic energizer and weight loss support supplement that works with your body to transform fat and build lean muscle.When reaching your weight loss goals, it is important to give your body all the tools it needs to support a faster metabolism, control appetite, with the energy, focus, and mood you need to perform at your best.Uncompromising quality standards backed up by researched ingredients, transparent formulas, and GMP certified.",
    },
    cat: "Proteins",
    pdf: "",
    extraInfo: "GMO-free",
    price: 680,
    img: "/images/transform.png",
  },
  {
    _id: 7,
    productName: "R1 CHARGED CREATINE SNOW CONE",
    ficheTech: [],
    brand: "Other",
    badge: true,
    des: {
      en: "R1 Charged Creatine’s refreshing fruit flavors are built to support an enhanced workout with hydration, energy, and greater training capacity.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 850,
    img: "/images/creatin.png",
  },
  {
    _id: 8,
    productName: "SPORT COMPLEX “RULE ONE PROTEINS",
    ficheTech: [],
    discount: 4420,
    brand: "Other",
    badge: false,
    des: {
      en: "Better output means we obsess over the input. That is why Rule 1 Proteins™ maintains tight control over the entire process. From formulation and ingredients sourcing to blending and packaging. Everything is done the right way in our US – based, state-of-the-art facility. Streamlining and tightly controlling every phase of the process enables us to offer premium products without the premium price.",
    },
    cat: "Proteins",
    pdf: "",
    extraInfo: "GMO-free",
    price: 4420,
    img: "/images/sportComplex.png",
  },
  {
    _id: 9,
    productName: "ALL 9 AMINO BCAAS & EAAS ORANGE CRANBERRY",
    ficheTech: [],
    brand: "Other",
    badge: false,
    des: {
      en: "With 10 grams total Essential Amino Acids (EAAs), including 7.2 grams of Branched Chain Amino Acids (BCAAs), ALL9 AminoTM is the ultimate goal-crushing muscle recovery formula. Experience the unrivaled and potent Essential Amino Acid formula in ALL9 that supports speedy muscle recovery and the Muscle Protein Synthesis process that is necessary for muscle growth.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 2040,
    img: "/images/amino.png",
  },
  {
    _id: 10,
    productName: "BCAA LEAN ENERGY BLUE RAZ",
    ficheTech: [],
    brand: "Other",
    badge: true,
    des: {
      en: "BCAA LEAN ENERGY is our most complete lean body performance fuel for anytime use with 5g of the highest quality BCAAs per serving combined with CLA, Acetyl-L-Carnitine and Maca Powder for fat burning and Beta-Alanine, L-Alanine and Taurine and to enhance endurance, recovery and focus. BCAA LEAN ENERGY uses natural energizers and antioxidants from Green Coffee and Green Tea for energy and focus. And if you’re on a low-carb or Keto diet, BCAA LEAN ENERGY can help support fat utilization and help fight fatigue often felt when in a calorie deficit. Make BCAA LEAN ENERGY your fuel for anytime energy, fat burning and performance.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 510,
    img: "/images/bcaa.png",
  },
  {
    _id: 11,
    productName: "SPORT COMPLEX “MASS POWER”",
    discount: 5100,
    ficheTech: [],
    brand: "Other",
    badge: false,
    des: {
      en: "The Mass Power Sport Complex offers a comprehensive solution to enhance muscle development and support weight gain. With its protein-rich components and convenient protein bars, it provides a convenient and effective way to fuel your body for optimal performance and size gains.",
    },
    cat: "Proteins",
    pdf: "",
    extraInfo: "GMO-free",
    price: 5100,
    img: "/images/masspower.png",
  },
  {
    _id: 12,
    productName: "ISO100 HYDROLYZED WHEY",
    ficheTech: [],
    brand: "Other",
    badge: true,
    des: {
      en: "ISO100 is simply muscle-building fuel. If your goal is gaining muscle size and strength, then ISO100 is your perfect workout partner. Loaded with muscle-building amino acids, ISO100 can support even the most serious resistance-training programs.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 2817.5,
    img: "/images/iso100.png",
  },
  {
    _id: 13,
    productName: "CLEAN MEAL SNICKERDOODLE",
    ficheTech: [],
    brand: "Other",
    badge: true,
    des: {
      en: "Never miss a meal again. Clean Meal™ is a quick and healthy meal replacement for people on the move. Scoop, shake, and, in just 60 seconds, you’ve got a complete meal packed with wholesome, whole-food nutrition: slow-burning carbs from Swedish oats and organic quinoa; organic coconut MCT oil; 21 vitamins and minerals from organic vegetables; and non-GMO whey protein isolate treated with ioWhey® technology for up to 123% better amino acid absorption*. Rich, creamy, and satisfying, reach for Clean Meal™ to replace up to two meals per day, or anytime you need a complete, nourishing meal on the go.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 1666.5,
    img: "/images/cleanmeal.png",
  },
  {
    _id: 14,
    productName: "Solgar 7",
    ficheTech: [],
    brand: "Solgar",
    badge: false,
    des: {
      en: "Solgar brings you the next generation in joint health. Introducing Solgar ®  7 Vegetable Capsules. This unique formulation targets multiple pathways to balance the release of joint enzymes, structurally support collagen building blocks and sensitive joint cartilage, while simultaneously supporting the body's range of natural motion and flexibility. The Vitamin C in this product helps collagen formation for the normal function of cartilage and bones. It also helps to protect cells from oxidative damage (stress). Suggested Use As a food supplement for adults, take one (1) vegetable capsule daily or as directed by a healthcare practitioner. Do not exceed directions for use. If you are pregnant, nursing, taking any medications or have any medical condition, please consult your healthcare practitioner before taking this product.",

      tr: "Solgar size ortak sağlıkta yeni nesli getiriyor. Solgar ®  7 Bitkisel Kapsüllerle Tanışın.Bu eşsiz formülasyon, eklem enzimlerinin salınımını dengelemek, kolajen yapı taşlarını ve hassas eklem kıkırdağını yapısal olarak desteklemek ve aynı zamanda vücudun doğal hareket ve esneklik aralığını desteklemek için birden fazla yolu hedefler.Bu üründeki C Vitamini, kıkırdak ve kemiklerin normal fonksiyonu için kolajen oluşumuna yardımcı olur. Ayrıca hücrelerin oksidatif hasardan (stres) korunmasına da yardımcı olur. Önerilen Kullanım Yetişkinler için gıda takviyesi olarak günde bir (1) bitkisel kapsül veya bir sağlık uygulayıcısının önerdiği şekilde alın. Kullanım talimatlarını aşmayın.Hamileyseniz, emziriyorsanız, herhangi bir ilaç kullanıyorsanız veya herhangi bir sağlık sorununuz varsa, lütfen bu ürünü almadan önce sağlık uzmanınıza danışın.",
    },

    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 2788,
    img: "/images/solgar7.jpg",
  },
  {
    _id: 15,
    productName: "Nature Plus Acerola-C 500mg",
    ficheTech: [],
    brand: "Nature plus",
    badge: false,
    des: {
      en: "Never miss a meal again. Clean Meal™ is a quick and healthy meal replacement for people on the move. Scoop, shake, and, in just 60 seconds, you’ve got a complete meal packed with wholesome, whole-food nutrition: slow-burning carbs from Swedish oats and organic quinoa; organic coconut MCT oil; 21 vitamins and minerals from organic vegetables; and non-GMO whey protein isolate treated with ioWhey® technology for up to 123% better amino acid absorption*. Rich, creamy, and satisfying, reach for Clean Meal™ to replace up to two meals per day, or anytime you need a complete, nourishing meal on the go.",

      tr: "C vitamini dünyada en çok bilinen ve en çok saygı duyulan vitamindir: Bu antioksidan, damar sistemi ve doğal savunmalar da dahil olmak üzere vücudun birçok sistemini etkiler. Nature's plus Acerola-C, Acerola'nın sağlıklı ve lezzetli özelliklerini limon, kuşburnu, siyah kuş üzümü, yeşil biber ve Saphora Japonica'dan oluşan sinerjik besinlerle birleştirerek benzersiz bir C Vitamini takviyesi sağlar. Limon Bioflavoind kompleksi (Narenciye limon meyvesinden) 100mg, Kuşburnu ekstresi (rosa canina meyvesinden) 25mg, Siyah güncel meyve konsantresi 25mg, Yeşil biber özü (Capsicum annuum meyvesinden) 25mg, Rutin (Saphora japonica yaprağından) 5mg, Fruktoz , Doğal tatlar , Magnezyum stearat",
    },
    cat: "Vitamins",
    pdf: "",
    extraInfo: "GMO-free",
    price: 430,
    img: "/images/acerolac.jpg",
  },
  {
    _id: 16,
    productName: "Nature Plus Cal/Mag/Vit D3",
    ficheTech: [],
    brand: "Nature plus",
    badge: false,
    des: {
      en: "Strong bones are the foundation of good health! High potency Nature´s Plus Cal/Mag/Vit D3 with Vitamin K2, in delicious chocolate or vanilla chewables, is an advanced formulation, employing the most effective and bioavailable bone nutrients available. A potent combination of calcium and magnesium form the basis of skeletal structure. But only Nature´s Plus Cal/Mag/Vit D3 with K2 comes supercharged with 1000 IU of Vitamin D3 and 100 mcg of K2 (menatetrenone), the most effective form of Vitamin K, for superior absorption and deposition of essential bone minerals. For complete skeletal support and an overall feeling of health, well-being and vitality, choose Nature´s Plus Cal/Mag/Vit D3 with K2! Nature´s Plus Cal/Mag/Vit D3 with Vitamin K2 conforms to the strictest standards for purity.",
      tr: "Güçlü kemikler sağlığın temelidir! Yüksek etkili Nature's Plus Cal/Mag/Vit D3 ve K2 Vitamini, lezzetli çikolata veya vanilyalı çiğnenebilir ürünlerde, mevcut en etkili ve biyoyararlı kemik besinlerini kullanan gelişmiş bir formülasyondur. Güçlü bir kalsiyum ve magnezyum kombinasyonu iskelet yapısının temelini oluşturur. Ancak yalnızca Nature's Plus Cal/Mag/Vit D3 with K2, temel kemik minerallerinin üstün emilimi ve birikmesi için 1000 IU Vitamin D3 ve 100 mcg K2 (menatetrenon) ile güçlendirilmiş olarak gelir; K Vitamininin en etkili formudur. Tam iskelet desteği ve genel sağlık, esenlik ve canlılık hissi için Nature's Plus Cal/Mag/Vit D3 with K2'yi seçin! Nature's Plus Cal/Mag/Vit D3 ve K2 Vitamini, saflık açısından en katı standartlara uygundur.",
    },
    cat: "Vitamins",
    pdf: "",
    extraInfo: "GMO-free",
    price: 410,
    img: "/images/NATURECAL-MAG.jpg",
  },
  {
    _id: 17,
    productName: "Nature's Plus Source of Life Garden Vitamin K2",
    ficheTech: [],
    brand: "Nature plus",
    badge: false,
    des: {
      en: "Organic Gold Standard Whole Food K2 (m7) GROWN FROM CERTIFIED ORGANIC WHOLE FOODS. Source of Life Garden™ Vitamin K2 Caps with Organic Gold Standard Nutrients is the first vitamin K2 supplement made to exacting organic standards. Each easy-to-swallow capsule provides 120 mcg of vitamin K2, the most bioavailable form of this critical bone-health nutrient, as menaquinone-7 from organic natto (a fermented soy food).",
      tr: "Organic Gold Standard Tam Gıda K2 (m7) SERTİFİKALI ORGANİK BÜTÜN GIDALARDAN YETİŞTİRİLMİŞTİR. Organik Altın Standart Besin Maddelerine sahip Life Garden™ Vitamin K2 Kapakları, sıkı organik standartlara uygun olarak üretilen ilk K2 vitamini takviyesidir. Kolayca yutulabilen her bir kapsül, organik natto'dan (fermente bir soya gıdası) elde edilen menakinon-7 olarak, bu kritik kemik sağlığı besin maddesinin biyoyararlanımı en yüksek formu olan 120 mcg K2 vitamini sağlar.",
    },
    cat: "Vitamins",
    pdf: "",
    extraInfo: "GMO-free",
    price: 400,
    img: "/images/sourceoflife.jpg",
  },
  {
    _id: 18,
    productName: "Pukka Chlorella Tablet",
    ficheTech: [],
    brand: "Pukka",
    badge: false,
    des: {
      en: "Chlorella has an amazing balance of nutrients that cleanse , alkalise and protect the body with a special focus on supporting immunity. It´s ability to capture natures energy gives it a unique nutritional profile including a high chlorophyll content which is useful for cleansing. it is also high in chlorella growth factor, a special compound know to support the immune system. It is one of the most nutritionally dense foods in the world filled with antioxidants, amino acids, proteins, essential fatty acids, vitamins, minerals and nucleic acids. 100% organic, ethically sourced, suitable for vegetarian and vegans.",
      tr: "Chlorella, bağışıklığı desteklemeye özel olarak odaklanarak vücudu temizleyen, alkalileştiren ve koruyan inanılmaz bir besin dengesine sahiptir.Doğanın enerjisini yakalama yeteneği ona, temizlik için yararlı olan yüksek klorofil içeriği de dahil olmak üzere benzersiz bir beslenme profili kazandırır. aynı zamanda bağışıklık sistemini desteklediği bilinen özel bir bileşik olan chlorella büyüme faktörü açısından da yüksektir. Antioksidanlar, amino asitler, proteinler, esansiyel yağ asitleri, vitaminler, mineraller ve nükleik asitlerle dolu, dünyadaki besin açısından en yoğun gıdalardan biridir. %100 organik, etik kaynaklı, vejetaryen ve veganlar için uygundur.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 550,
    img: "/images/chlorella.jpg",
  },
  {
    _id: 19,
    productName: "Pukka Vitalise",
    ficheTech: [],
    brand: "Pukka",
    badge: false,
    des: {
      en: "Vitalise is a vibrant nutritional blend containing 30 organic ingredients including concentrated extracts from 10 herbs and spices, 7 fruits, 2 vegetables, 3 seaweeds, 2 mushrooms, 2 freshwater plants, 1 grass juice and magical flower pollen. Made with some of nature’s finest herbs, grown in fertile organic soils, it captures the incredible essence of nature’s bounty. What does Vitalise do? Vitalise combined with a balanced and varied diet, helps you to maintain energy levels, deal with the stresses of modern life, while helping you live life to the full. This broad-spectrum formula contains the highest organic grade, sustainably cultivated fruits and herbs, carefully selected to bring you the full potential of nature’s goodness. Ingredients 100% organic agricultural ingredients: Beetroot juice crystals 13%, Amla fruit powder, Slippery Elm bark, Wheat Grass juice powder 30:1, Carrot juice crystals Acerola fruit concentrate, Flower pollen, Spirulina, Licorice root, Peppermint leaf, Bilberry fruit fresh freeze dried 8:1 4%, Chlorella cracked-cell, Amla fruit juice freeze dried crystals 20:1, Pomegranate fruit juice freeze dried crystals, Seagreens® Arctic fresh seaweed blend, Cordyceps full-spectrum, Reishi full-spectrum, Cranberry fruit fresh freeze dried 10:1, Turmeric root wholistic extract, Holy Basil leaf wholistic extract, Ginger root wholistic extract, Cinnamon bark wholistic extract, Red Ginseng root 1%, Vitamin B Complex Orgen-B’s™ (Holy Basil, Lemon and Guava fruit extracts), Aloe Vera juice concentrate 200:1, Green tea leaf aqueous extract.",
      tr: "Vitalise, 10 bitki ve baharat, 7 meyve, 2 sebze, 3 deniz yosunu, 2 mantar, 2 tatlı su bitkisi, 1 çim suyu ve sihirli çiçek poleninden elde edilen konsantre özler dahil 30 organik içerik içeren canlı bir besin karışımıdır. Verimli organik topraklarda yetişen, doğanın en iyi bitkilerinden bazılarıyla yapılan bu ürün, doğanın cömertliğinin inanılmaz özünü yakalar.Vitalise ne işe yarar? Dengeli ve çeşitli bir beslenmeyle birleştirilen Vitalise, enerji seviyenizi korumanıza, modern yaşamın stresleriyle başa çıkmanıza ve hayatı dolu dolu yaşamanıza yardımcı olur. Bu geniş spektrumlu formül, size doğanın iyiliğinin tam potansiyelini sunmak için özenle seçilmiş, en yüksek organik sınıfı, sürdürülebilir şekilde yetiştirilen meyveleri ve bitkileri içerir. İçindekiler %100 organik tarımsal içerikler: Pancar suyu kristalleri %13, Amla meyve tozu, Kaygan Karaağaç kabuğu, Buğday Çimi suyu tozu 30:1, Havuç suyu kristalleri Acerola meyve konsantresi, Çiçek poleni, Spirulina, Meyan kökü, Nane yaprağı, Yabanmersini meyvesi taze dondurma kurutulmuş 8:1 %4, Chlorella çatlak hücreli, Amla meyve suyu dondurularak kurutulmuş kristaller 20:1, Nar meyve suyu dondurularak kurutulmuş kristaller, Seagreens® Arctic taze deniz yosunu karışımı, Cordyceps tam spektrumlu, Reishi tam spektrumlu, Kızılcık meyvesi taze dondurulmuş kurutulmuş 10:1, Zerdeçal kökü bütünsel özü, Kutsal Fesleğen yaprağı bütünsel özü, Zencefil kökü bütünsel özü, Tarçın kabuğu bütünsel özü, Kırmızı Ginseng kökü %1, B Vitamini Kompleksi Orgen-B's™ (Kutsal Fesleğen, Limon ve Guava meyve özleri), Aloe Vera suyu konsantresi 200:1, Yeşil çay yaprağı sulu ekstraktı.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 710,
    img: "/images/vitalise.jpg",
  },
  {
    _id: 20,
    productName: "Solaray AlphaActin",
    ficheTech: [],
    brand: "Solaray",
    badge: false,
    des: {
      en: "Supplementation of Probiotics helps us to replenish the good bacteria that live in the gut, which may deplete due to stress, use of antibiotics, high oestrogen levels, yeast infection or poor digestion.The enteric-coated capsule provides assurance that the contents will survive the acidic environment of the stomach and break down in the small intestine. Proven Activity Without Refrigeration. Directions: Take 1 capsule daily with a meal or glass of water. Ingredients: L. acidophilus (La-5), B. lactis (Bificum), Capsule (Gelatine), Dextrose, Magnesium Stearate (Vegetable Source). Allergen Advice: Contains Milk. Caution: Keep out of reach of children. Women who are pregnant or planning pregnancy should consult their doctor befor taking food supplements. Do not exceed recommended daily intake.",
      tr: "Probiyotik takviyesi, bağırsakta yaşayan ve stres, antibiyotik kullanımı, yüksek östrojen seviyeleri, maya enfeksiyonu veya zayıf sindirim nedeniyle tükenebilen iyi bakterileri yenilememize yardımcı olur. Enterik kaplı kapsül, içeriğin midenin asidik ortamında hayatta kalacağına ve ince bağırsakta parçalanacağına dair güvence sağlar. Soğutma Olmadan Kanıtlanmış Etkinlik. Talimatlar: Günde 1 kapsül yemek veya bir bardak su ile alın. İçindekiler: L. acidophilus (La-5), B. lactis (Bificum), Kapsül (Jelatin), Dekstroz, Magnezyum Stearat (Bitkisel Kaynak). Alerjen Tavsiyesi:  Süt İçerir. Dikkat: Çocukların ulaşamayacağı yerde saklayın. Hamile olan veya hamilelik planlayan kadınların gıda takviyesi almadan önce doktorlarına danışmaları gerekmektedir. Önerilen günlük alım miktarını aşmayın.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 765,
    img: "/images/acidopl.jpg",
  },
  {
    _id: 21,
    productName: "Solaray CranActin",
    ficheTech: [],
    brand: "Solaray",
    badge: false,
    des: {
      en: "A unique extract for relieving the symptoms of urinary tract infections with a guaranteed anti-adherence factor assuring that bacteria will not stick to the urethra causing re infection. Cranberry stimulates the production of Hippuric acid which also has an antibiotic effect on the urinary tract. Directions: Take 1 capsule with water, 2 to 4 times throughout the day Warnings: Keep out of reach of children. Women who are pregnant or planning pregnancy should consult their doctor before taking food supplements. Do not exceed recommended daily intake. Ingredients: Cranberry, Hydroxypropylmethyl Cellulose Capsule, Ascorbic Acid, Magnesium Hydroxide, Magnesium Oxide, Magnesium Stearate (Vegetable Source), Silica, Vegetable Juice Concentrate, Allergen Free.",
      tr: "Bakterilerin üretraya yapışıp yeniden enfeksiyona neden olmamasını garantileyen, garantili bir yapışma önleme faktörü ile idrar yolu enfeksiyonlarının semptomlarını hafifletmeye yönelik benzersiz bir ekstrakt. Kızılcık idrar yolu üzerinde antibiyotik etkisi de olan Hippurik asit üretimini uyarır. Talimatlar: Gün boyunca 2 ila 4 kez su ile 1 kapsül alın. Uyarılar: Çocukların ulaşamayacağı yerde saklayın. Hamile olan veya hamilelik planlayan kadınların gıda takviyesi almadan önce doktorlarına danışmaları gerekmektedir. Önerilen günlük alım miktarını aşmayın. İçindekiler: Kızılcık, Hidroksipropilmetil Selüloz Kapsülü, Askorbik Asit, Magnezyum Hidroksit, Magnezyum Oksit, Magnezyum Stearat (Bitkisel Kaynak), Silika, Sebze Suyu Konsantresi, Alerjen içermez.",
    },
    cat: "",
    pdf: "",
    extraInfo: "GMO-free",
    price: 493,
    img: "/images/cranactin.jpg",
  },
  {
    _id: 22,
    productName: "Pukka Turmeric",
    ficheTech: [],
    brand: "Pukka",
    badge: false,
    des: {
      en: "100% organically grown and ethically sourced.Ingredients:Turmeric root (40%), Suoi Gang green tea (20%), licorice root.cardamon pod, lemon Vana tulsi leaf.lemon essential oil flavour (6%).lemon whole (6%)",
      tr: "%100 organik olarak yetiştirilmiş ve etik kaynaklıdır.İçindekiler:Zerdeçal kökü (%40), Suoi Gang yeşil çayı (%20), meyan kökü.kakule kabuğu, limon Vana tulsi yaprağı.limon esansiyel yağı aroması (%6).Limon bütün (6%)",
    },
    cat: "Herbal Teas",
    pdf: "",
    extraInfo: "GMO-free",
    price: 20,
    img: "/images/turmeric.jpg",
  },
  {
    _id: 23,
    productName: "Pukka Clean",
    ficheTech: [],
    brand: "Pukka",
    badge: false,
    des: {
      en: "Clean Greens is a blend of super-rich green foods containing grass juice, leaf, vegetables, seed sprouts, sea greens, freshwater plants and digestive herbs.Made with some of nature's finest herbs, grown in fertile organic soils it captures the incredible essence of nature's bounty.What does Clean Greens doClean Greens naturally support the body's ability to cope better with our polluted environment and supplement our diet.This broad-spectrum formula contains the highest organic grade, sustainably cultivated fruits and herbs, carefully selected to bring you the full potential of nature’s goodness",
      tr: "Clean Greens, çimen suyu, yaprak, sebze, tohum filizleri, deniz yeşillikleri, tatlı su bitkileri ve sindirime yardımcı otlar içeren süper zengin yeşil gıdaların bir karışımıdır.Doğanın en iyi otlarından bazılarıyla yapılan, verimli organik topraklarda yetiştirilen bu ürün, doğanın cömertliğinin inanılmaz özünü yansıtıyor.Clean Greens ne işe yarar?Clean Greens, vücudumuzun kirli çevreyle daha iyi başa çıkma yeteneğini doğal olarak destekler ve beslenmemizi destekler.Bu geniş spektrumlu formül, doğanın tüm iyiliğinden faydalanmanızı sağlamak için özenle seçilmiş, en yüksek organik kalitede, sürdürülebilir şekilde yetiştirilmiş meyve ve otları içerir.",
    },
    cat: "Herbal Teas",
    pdf: "",
    extraInfo: "GMO-free",
    price: 50,
    img: "/images/clean-greens.png",
  },
];